fix: naming (#3)
* Switch to using alpine for smaller images

* Use the tag

* Test alternative build structure

...with local registry for testing

* Don't need load with a local registry

* Need driver-opts argument to docker setup

* Try this setup

* Populate the tags properly

* Use the right registry

* Add math/Dockerfile as requested in #259

* kramdown doesn't need more now

* Add math image

* Build math image

* Test the alpine image

* Cache .targets.mk and save some time

* Latest image

* Install globally

* Missing python package

* Stop pushing everything to docker.io

* Include the registry in the docker files too

* Add note about empty files

Closes #258.

* Use the action image for CI

* Install svgcheck in the image

* Make setup-note.sh work on macOS

Bash case operators were added in Bash 4, and macOS runs a
version of Bash from the Paleolithic. This uses tr instead to
support older versions of Bash.

* Inline

* Get some metadata from the datatracker API for the note

* Unset entrypoint in circle image

* Stop using tools.ietf.org

* Update base URL options

* Use persistent connections to hopefully avoid DNS issues

* Use new kramdown feature

* Add notes about the meta image

* Archive when publishing too

Closes #190.

* Archive the right XML

* Update SETUP.md

I am in the process of getting myself setup as described here (thanks!). 
I am not sure if this was a typo or if things changed, but I needed to do "brew install libxslt" instead of "brew install libxslt1".

$ brew install libxslt1
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "libxslt1".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

* Update documentation for mac homebrew XML packages

* Migrate off tools.ietf.org

* Fix the link to REPO.md

* Generate CODEOWNERS

* Add CODEOWNERS to setup

Closes #240.

* Warn when there are no files to upload

* Remove archive_repo; rely on pip

* Doc for manual install

* Allow fetching default branch without credentials

On public GitHub repositories, the API call for the default
branch succeeds even without credentials. This PR changes
default-branch.py to attempt the API call even if there are
no credentials present.

* Suppress that warning

* Revert "Merge pull request #274 from MikeBishop/pip-archive"

This reverts commit ae206159dc0f53feb6490a2496268f78c3ed730b, reversing
changes made to 59f6a0e97b888e8ae074fe49efb38d499ddf43e0.

* Keep the dockerfile changes

* Incremental tweaks for RFCs in the repo

* Add XML tidy function

* Re-apply pull request #274 from MikeBishop/pip-archive

This reverts commit 0c203c61047d6d5b4bc0e57c4c4a718df8fe74c2.

* Update instructions; move to user installs

* Use persistent connections

* net-http-persistent needs to be installed too

* Cache the bibxml for BCP/STD

* Fix styling of RFC number

* pre-commit for RFCs too

* Break `make submit` so that Richard does the right thing

* Typo

* fix: [pull] main_from_martinthomson:main (#1)

* Sketch in support for per-draft issue links

Currently only supports Markdown drafts.

* Don't show issue if there's only one file

* add a columns to table header

* Make it work for XML

* extract-frontmatter -> extract-metadata

* more straightforward

* add python YAML

* xml also

* Update @mnot's patch to make it more robust

This passes in source files rather than relying on the cwd being
correct.  It also only passes one file in to the extract metadata
script.  That file is based on the input.

For HTTP, it also caches what it learns to avoid the extra work.  This
might run afoul of the ancient bash on mac not liking it.  We'll see.

* Yep, macs are just bad

* Fix the default branch if it is not right

* Fix default-branch test mess

* Add python yaml module to image

Co-authored-by: Mark Nottingham <mnot@mnot.net>
Co-authored-by: Martin Thomson <mt@lowentropy.net>

* Use math image on this branch (#2)

Co-authored-by: Martin Thomson <mt@lowentropy.net>

Co-authored-by: Martin Thomson <mt@lowentropy.net>
Co-authored-by: Lars Eggert <lars@eggert.org>
Co-authored-by: David Schinazi <DavidSchinazi@users.noreply.github.com>
Co-authored-by: Charles Eckel <eckelcu@cisco.com>
Co-authored-by: Lucas Pardue <lucaspardue.24.7@gmail.com>
Co-authored-by: Jeffrey Yasskin <jyasskin@google.com>
Co-authored-by: Mike Bishop <mbishop@evequefou.be>
Co-authored-by: David Schinazi <dschinazi@google.com>
Co-authored-by: pull[bot] <39814207+pull[bot]@users.noreply.github.com>
Co-authored-by: Mark Nottingham <mnot@mnot.net>